site_name: iot-air-pollution Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'luismayta/iot-air-pollution'
repo_url: 'https://github.com/luismayta/iot-air-pollution'

google_analytics:
  - ''
  - 'auto'
