# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # PostgreSQL database.
  db:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=air-pollution
    volumes:
      - db:/var/lib/postgresql/data # Using the declared volume.
      - .:/usr/src

  # Python
  app:
    image: air_pollution-app-dev
    environment: &environment
      - STAGE=local
      - DB_URL=postgis://postgres:postgres@db:5432/air-pollution
    build:
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
    depends_on:
      - db

  zappa:
    image: air_pollution-zappa-dev
    environment:
      - STAGE=local
    build:
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env

  check:
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env

volumes:
  db:
